package mercury.runtime;

import java.util.ArrayList;
import java.util.List;

import cucumber.api.Scenario;
import mercury.api.models.resource.Resource;
import mercury.pageobject.web.LoginPage;
import mercury.pageobject.web.NotificationPage;
import mercury.pageobject.web.PasswordResetRequestPage;
import mercury.pageobject.web.PopupAlert;
import mercury.pageobject.web.ResetPasswordPage;
import mercury.pageobject.web.admin.AdminAddNewAssetPage;
import mercury.pageobject.web.admin.AdminAddNewPpmTypePage;
import mercury.pageobject.web.admin.AdminAddNewResourcePage;
import mercury.pageobject.web.admin.AdminAddNewResourceProfilePage;
import mercury.pageobject.web.admin.AdminAddNewUserPage;
import mercury.pageobject.web.admin.AdminAddNewUserProfilePage;
import mercury.pageobject.web.admin.AdminAssetsPage;
import mercury.pageobject.web.admin.AdminConfigureExceptionModal;
import mercury.pageobject.web.admin.AdminComplianceConfigPage;
import mercury.pageobject.web.admin.AdminEditAssetPage;
import mercury.pageobject.web.admin.AdminEditIncidentCriteriaPage;
import mercury.pageobject.web.admin.AdminEditOrderWidget;
import mercury.pageobject.web.admin.AdminEditResourcePage;
import mercury.pageobject.web.admin.AdminEditResourceProfilePage;
import mercury.pageobject.web.admin.AdminEditSiteConfigurationModal;
import mercury.pageobject.web.admin.AdminEditUserPage;
import mercury.pageobject.web.admin.AdminEditUserProfilePage;
import mercury.pageobject.web.admin.AdminHomePage;
import mercury.pageobject.web.admin.AdminImportConfigurationPage;
import mercury.pageobject.web.admin.AdminIncidentConfigurationPage;
import mercury.pageobject.web.admin.AdminMenuPage;
import mercury.pageobject.web.admin.AdminNewIncidentCriteriaPage;
import mercury.pageobject.web.admin.AdminOrganisationPage;
import mercury.pageobject.web.admin.AdminPpmTypeAssetMappingPage;
import mercury.pageobject.web.admin.AdminPpmTypeAssetPage;
import mercury.pageobject.web.admin.AdminPpmsPage;
import mercury.pageobject.web.admin.AdminQuestionPage;
import mercury.pageobject.web.admin.AdminResourcesAndUsersPage;
import mercury.pageobject.web.admin.AdminRulePage;
import mercury.pageobject.web.admin.AdminRulesEnginePage;
import mercury.pageobject.web.admin.AdminSystemFeatureTogglePage;
import mercury.pageobject.web.admin.companies.AdminCompaniesAddAssignmentRulePage;
import mercury.pageobject.web.admin.companies.AdminCompaniesAssignmentRuleDeleteModal;
import mercury.pageobject.web.admin.companies.AdminCompaniesAssignmentRuleEditPage;
import mercury.pageobject.web.admin.companies.AdminCompaniesAssignmentRulesPage;
import mercury.pageobject.web.admin.companies.AdminCompaniesEditAssignmentRuleModal;
import mercury.pageobject.web.admin.companies.AdminCompaniesPage;
import mercury.pageobject.web.admin.companies.AdminEditCompanyAdditionalDetailsPartial;
import mercury.pageobject.web.admin.companies.AdminEditCompanyAliasesPartial;
import mercury.pageobject.web.admin.companies.AdminEditCompanyCoreDetailsPartial;
import mercury.pageobject.web.admin.companies.AdminEditCompanyPage;
import mercury.pageobject.web.admin.companies.AdminEditCompanySaveModal;
import mercury.pageobject.web.admin.finance.AdminFinancePage;
import mercury.pageobject.web.admin.jobs.AdminJobStatusEditPage;
import mercury.pageobject.web.admin.jobs.AdminJobsPage;
import mercury.pageobject.web.admin.jobs.OnCallSchedulerAdminPage;
import mercury.pageobject.web.admin.refrigerantGasUsage.AdminLeakSiteInformationModal;
import mercury.pageobject.web.admin.refrigerantGasUsage.AdminRefrigerantGasUsageEditPage;
import mercury.pageobject.web.admin.refrigerantGasUsage.AdminRefrigerantGasUsageEditPageV2;
import mercury.pageobject.web.admin.refrigerantGasUsage.AdminRefrigerantGasUsageSearchPage;
import mercury.pageobject.web.admin.refrigerantGasUsage.AdminRefrigerantSourceModal;
import mercury.pageobject.web.admin.sites.AdminEditSitePage;
import mercury.pageobject.web.admin.sites.AdminEditSiteTypePage;
import mercury.pageobject.web.admin.sites.AdminSiteTypesPage;
import mercury.pageobject.web.admin.sites.AdminSitesPage;
import mercury.pageobject.web.helpdesk.HelpdeskCancelApprovedUpliftPanel;
import mercury.pageobject.web.helpdesk.HelpdeskCoreDetails;
import mercury.pageobject.web.helpdesk.HelpdeskHomePage;
import mercury.pageobject.web.helpdesk.HelpdeskNavBar;
import mercury.pageobject.web.helpdesk.HelpdeskResourceETAPanel;
import mercury.pageobject.web.helpdesk.HelpdeskSearchBar;
import mercury.pageobject.web.helpdesk.HelpdeskSitePage;
import mercury.pageobject.web.helpdesk.HelpdeskTimelineTab;
import mercury.pageobject.web.helpdesk.caller.EditCallerModal;
import mercury.pageobject.web.helpdesk.caller.HelpdeskAddCallerPage;
import mercury.pageobject.web.helpdesk.caller.HelpdeskCallerPage;
import mercury.pageobject.web.helpdesk.caller.HelpdeskContactsTab;
import mercury.pageobject.web.helpdesk.caller.NewCallerPage;
import mercury.pageobject.web.helpdesk.incidents.HelpdeskCancelIncidentPage;
import mercury.pageobject.web.helpdesk.incidents.HelpdeskIncidentActionsDropdown;
import mercury.pageobject.web.helpdesk.incidents.HelpdeskIncidentAnswersTab;
import mercury.pageobject.web.helpdesk.incidents.HelpdeskIncidentEscalation;
import mercury.pageobject.web.helpdesk.incidents.HelpdeskIncidentEscalationAdditionalContact;
import mercury.pageobject.web.helpdesk.incidents.HelpdeskIncidentEscalationContactEmailSmsTab;
import mercury.pageobject.web.helpdesk.incidents.HelpdeskIncidentEscalationTab;
import mercury.pageobject.web.helpdesk.incidents.HelpdeskIncidentFollowUpPage;
import mercury.pageobject.web.helpdesk.incidents.HelpdeskIncidentMonitorPage;
import mercury.pageobject.web.helpdesk.incidents.HelpdeskIncidentSendEscalation;
import mercury.pageobject.web.helpdesk.incidents.HelpdeskIncidentTimelineTab;
import mercury.pageobject.web.helpdesk.incidents.HelpdeskIncidentUpdate;
import mercury.pageobject.web.helpdesk.incidents.HelpdeskIncidentsLinkedJobsModal;
import mercury.pageobject.web.helpdesk.incidents.HelpdeskJobsLinkedIncidentsPanel;
import mercury.pageobject.web.helpdesk.incidents.HelpdeskLogAnIncidentPage;
import mercury.pageobject.web.helpdesk.incidents.HelpdeskViewIncidentPage;
import mercury.pageobject.web.helpdesk.jobs.AddJobNotesModal;
import mercury.pageobject.web.helpdesk.jobs.CancelChangesAlert;
import mercury.pageobject.web.helpdesk.jobs.ConfirmJobChangesModal;
import mercury.pageobject.web.helpdesk.jobs.ConfirmWarrantyPanel;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskAcceptJobPanel;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskAddAttachmentsModal;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskAddOrOverrideAbsencePanel;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskAssetPage;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskCallJobContactModal;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskCancelJobChasePanel;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskCreateJobChasePanel;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskDeclineJobPanel;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskDocumentsTab;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskFundingRequestsPanel;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskJobActionsPanel;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskJobCancelPanel;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskJobChasePanel;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskJobPage;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskLinkedIncidentsModal;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskLinkedJobsModal;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskLogJobPage;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskNewSiteContactModal;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskOpenJobsTab;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskParkJobPanel;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskPreviousFundingRequestsPanel;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskQuestionsTab;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskQuotesPanel;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskTransferWorkPanel;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskTriagePanel;
import mercury.pageobject.web.helpdesk.jobs.HelpdeskUpdateJobChasePanel;
import mercury.pageobject.web.helpdesk.jobs.ReopenJobModal;
import mercury.pageobject.web.helpdesk.monitors.MonitorGrid;
import mercury.pageobject.web.helpdesk.monitors.MonitorsForInfo;
import mercury.pageobject.web.helpdesk.monitors.MonitorsSettings;
import mercury.pageobject.web.helpdesk.monitors.MonitorsToDo;
import mercury.pageobject.web.helpdesk.resources.HelpdeskAcknowledgeETAPanel;
import mercury.pageobject.web.helpdesk.resources.HelpdeskAddAdditionalResourcePanel;
import mercury.pageobject.web.helpdesk.resources.HelpdeskAdditionalResourcePanel;
import mercury.pageobject.web.helpdesk.resources.HelpdeskAdditionalResourcesNotRequiredPanel;
import mercury.pageobject.web.helpdesk.resources.HelpdeskAdditionalResourcesRequiredPanel;
import mercury.pageobject.web.helpdesk.resources.HelpdeskAdviseEtaPanel;
import mercury.pageobject.web.helpdesk.resources.HelpdeskAdviseRemovalPanel;
import mercury.pageobject.web.helpdesk.resources.HelpdeskManageResourcesPanel;
import mercury.pageobject.web.helpdesk.resources.HelpdeskRemoveResourcePanel;
import mercury.pageobject.web.helpdesk.resources.HelpdeskResourcePage;
import mercury.pageobject.web.helpdesk.resources.HelpdeskResourcesTab;
import mercury.pageobject.web.helpdesk.resources.HelpdeskScheduleCallBackPanel;
import mercury.pageobject.web.pageHelpers.QuestionHelper;
import mercury.pageobject.web.portal.JobQuestions;
import mercury.pageobject.web.portal.PortalHomePage;
import mercury.pageobject.web.portal.PortalNavBar;
import mercury.pageobject.web.portal.PortalSummaryPage;
import mercury.pageobject.web.portal.admin.ManageDeptHeadUserAssignmentPage;
import mercury.pageobject.web.portal.creditnotes.AddNewCreditNoteLineModal;
import mercury.pageobject.web.portal.creditnotes.AllCreditNotesAwaitingApprovalPage;
import mercury.pageobject.web.portal.creditnotes.CreateCreditNotePage;
import mercury.pageobject.web.portal.creditnotes.CreditNoteApprovalPage;
import mercury.pageobject.web.portal.creditnotes.CreditNoteLinesModal;
import mercury.pageobject.web.portal.creditnotes.CreditNotePage;
import mercury.pageobject.web.portal.creditnotes.EnterCreditNoteDetailsPage;
import mercury.pageobject.web.portal.creditnotes.RejectCreditNoteModal;
import mercury.pageobject.web.portal.creditnotes.UploadCreditNoteDocumentPage;
import mercury.pageobject.web.portal.fundingrequests.FundingRequestQueriesPage;
import mercury.pageobject.web.portal.fundingrequests.FundingRequestsAwaitingApprovalPage;
import mercury.pageobject.web.portal.fundingrequests.FundingRequestsAwaitingResponseReviewPage;
import mercury.pageobject.web.portal.fundingrequests.FundingRequestsAwaitingReviewPage;
import mercury.pageobject.web.portal.fundingrequests.FundingRequestsPendingQueryResponsePage;
import mercury.pageobject.web.portal.fundingrequests.FundingRequestsRejectedPage;
import mercury.pageobject.web.portal.fundingrequests.InitialFundingRequestsApprovalPage;
import mercury.pageobject.web.portal.fundingrequests.InitialFundingRequestsPage;
import mercury.pageobject.web.portal.fundingrequests.JobDetailsPartial;
import mercury.pageobject.web.portal.fundingrequests.QueryInitialApproverModal;
import mercury.pageobject.web.portal.fundingrequests.SubmitFundingRequestModalPage;
import mercury.pageobject.web.portal.invoices.AddNewInvoiceLineModal;
import mercury.pageobject.web.portal.invoices.AddOrderLineToInvoiceModal;
import mercury.pageobject.web.portal.invoices.AddOrderLinesToInvoiceConfirmationModal;
import mercury.pageobject.web.portal.invoices.AllInvoicesAwaitingApprovalPage;
import mercury.pageobject.web.portal.invoices.AllOrdersPage;
import mercury.pageobject.web.portal.invoices.ApproveInvoiceModalPage;
import mercury.pageobject.web.portal.invoices.ClosedownTab;
import mercury.pageobject.web.portal.invoices.ConsolidatedInvoicesInProgressPage;
import mercury.pageobject.web.portal.invoices.DeleteInvoiceDocModal;
import mercury.pageobject.web.portal.invoices.EditInvoiceLineConfirmationModal;
import mercury.pageobject.web.portal.invoices.EditInvoiceLineModal;
import mercury.pageobject.web.portal.invoices.InvoiceApprovalPage;
import mercury.pageobject.web.portal.invoices.InvoiceDeleteInvoiceTemplateModal;
import mercury.pageobject.web.portal.invoices.InvoiceDetailsPage;
import mercury.pageobject.web.portal.invoices.InvoiceFinalApprovalPage;
import mercury.pageobject.web.portal.invoices.InvoiceLinesModal;
import mercury.pageobject.web.portal.invoices.InvoicePendingReviewPage;
import mercury.pageobject.web.portal.invoices.InvoiceReassignApproverPage;
import mercury.pageobject.web.portal.invoices.InvoiceSubmittedPage;
import mercury.pageobject.web.portal.invoices.InvoiceTab;
import mercury.pageobject.web.portal.invoices.InvoiceTemplatePage;
import mercury.pageobject.web.portal.invoices.InvoiceTemplatesPage;
import mercury.pageobject.web.portal.invoices.InvoiceViewPage;
import mercury.pageobject.web.portal.invoices.InvoicesAndCreditsAllOrders;
import mercury.pageobject.web.portal.invoices.InvoicesAndCreditsAwaitingReviewPage;
import mercury.pageobject.web.portal.invoices.InvoicesAwaitingApprovalPage;
import mercury.pageobject.web.portal.invoices.InvoicesAwaitingFinalApprovalPage;
import mercury.pageobject.web.portal.invoices.InvoicesAwaitingReviewPage;
import mercury.pageobject.web.portal.invoices.JobCostsTab;
import mercury.pageobject.web.portal.invoices.JobNotesTab;
import mercury.pageobject.web.portal.invoices.ManageInvoiceLinesModal;
import mercury.pageobject.web.portal.invoices.NewInvoicingEditInvoiceLineModal;
import mercury.pageobject.web.portal.invoices.OrdersAwaitingInvoicePage;
import mercury.pageobject.web.portal.invoices.PortalConsolidatedInvoicePage;
import mercury.pageobject.web.portal.invoices.PortalOrdersInvoicePage;
import mercury.pageobject.web.portal.invoices.RejectInvoiceModalPage;
import mercury.pageobject.web.portal.invoices.RejectInvoicePendingReviewModal;
import mercury.pageobject.web.portal.invoices.SubmittedInvoicesAndCreditsPage;
import mercury.pageobject.web.portal.invoices.UpliftsTab;
import mercury.pageobject.web.portal.invoices.UploadInvoiceDocumentPage;
import mercury.pageobject.web.portal.invoices.UploadInvoiceDocumentsPage;
import mercury.pageobject.web.portal.jobs.AcceptJobPage;
import mercury.pageobject.web.portal.jobs.AllJobsPage;
import mercury.pageobject.web.portal.jobs.AllJobsPage_OpsDirector;
import mercury.pageobject.web.portal.jobs.AsbestosModal;
import mercury.pageobject.web.portal.jobs.ChooseAssetPage;
import mercury.pageobject.web.portal.jobs.ContactInfoJobDetailsPage;
import mercury.pageobject.web.portal.jobs.CreatePartRequestModalPage;
import mercury.pageobject.web.portal.jobs.FeedbackDetailsModal;
import mercury.pageobject.web.portal.jobs.FeedbackPage;
import mercury.pageobject.web.portal.jobs.FeedbackResponsePage;
import mercury.pageobject.web.portal.jobs.JobDetailsPage;
import mercury.pageobject.web.portal.jobs.JobHistoryPage;
import mercury.pageobject.web.portal.jobs.JobInfoJobDetailsPage;
import mercury.pageobject.web.portal.jobs.JobLoggedConfigmationPage;
import mercury.pageobject.web.portal.jobs.OpenAwaitingJobsPage;
import mercury.pageobject.web.portal.jobs.PartsRequestPage;
import mercury.pageobject.web.portal.jobs.PortalJobsForSitePage;
import mercury.pageobject.web.portal.jobs.PortalLogAJobPage;
import mercury.pageobject.web.portal.jobs.PortalOpenJobsBySitePage;
import mercury.pageobject.web.portal.jobs.PortalStartWorkModalPage;
import mercury.pageobject.web.portal.jobs.PortalUpdateJobETA;
import mercury.pageobject.web.portal.jobs.ReplyToStoreModal;
import mercury.pageobject.web.portal.jobs.SiteInfoJobDetailsPage;
import mercury.pageobject.web.portal.jobs.SpokeToStoreModal;
import mercury.pageobject.web.portal.jobs.UpdateJobPage;
import mercury.pageobject.web.portal.jobs.UpdateSavedPage;
import mercury.pageobject.web.portal.jobs.refrigerant.PortalAppliancePartial;
import mercury.pageobject.web.portal.jobs.refrigerant.PortalLeakCheckAppliancePartial;
import mercury.pageobject.web.portal.jobs.refrigerant.PortalLeakSiteInformationModal;
import mercury.pageobject.web.portal.jobs.refrigerant.PortalLeakSiteInformationPartial;
import mercury.pageobject.web.portal.jobs.refrigerant.PortalRefrigerantMaxChargePartial;
import mercury.pageobject.web.portal.jobs.refrigerant.PortalRefrigerantSourceModal;
import mercury.pageobject.web.portal.jobs.refrigerant.PortalRefrigerantSourcePartial;
import mercury.pageobject.web.portal.jobs.refrigerant.PortalRefrigerantVersion1;
import mercury.pageobject.web.portal.multiquote.MultiQuoteAwaitingBypassApprovalPage;
import mercury.pageobject.web.portal.multiquote.MultiQuoteAwaitingBypassReviewPage;
import mercury.pageobject.web.portal.multiquote.MultiQuoteAwaitingQuotePage;
import mercury.pageobject.web.portal.multiquote.MultiQuoteAwaitingResourceSelectionPage;
import mercury.pageobject.web.portal.multiquote.MultiQuoteAwaitingReviewPage;
import mercury.pageobject.web.portal.parts.PartsOrderAwaitingApprovalPage;
import mercury.pageobject.web.portal.parts.PartsRequestsAwaitingApprovalPage;
import mercury.pageobject.web.portal.ppm.PPMAddCertificatesModal;
import mercury.pageobject.web.portal.ppm.PPMGasSafetyAdviceNoticeModal;
import mercury.pageobject.web.portal.ppm.PPMJobDetailsPage;
import mercury.pageobject.web.portal.ppm.PPMRemedialJobPage;
import mercury.pageobject.web.portal.ppm.PPMRequestQuotePage;
import mercury.pageobject.web.portal.quotes.AddQuoteLinePage;
import mercury.pageobject.web.portal.quotes.CreateQuotePage;
import mercury.pageobject.web.portal.quotes.DeclineInvitationToQuotePage;
import mercury.pageobject.web.portal.quotes.DeleteQuoteLinePage;
import mercury.pageobject.web.portal.quotes.EditQuoteDetailsPage;
import mercury.pageobject.web.portal.quotes.FundingRouteModal;
import mercury.pageobject.web.portal.quotes.JobAwaitingResourceAssignmentPage;
import mercury.pageobject.web.portal.quotes.JobsAwaitingQuotePage;
import mercury.pageobject.web.portal.quotes.JobsAwaitingResourceSelectionPage;
import mercury.pageobject.web.portal.quotes.ManagerJobsAwaitingQuotePage;
import mercury.pageobject.web.portal.quotes.OpenQuoteRequestsPage;
import mercury.pageobject.web.portal.quotes.QuoteAwaitingResourceQuotePage;
import mercury.pageobject.web.portal.quotes.QuoteJobDetailsPage;
import mercury.pageobject.web.portal.quotes.QuoteJobEdit;
import mercury.pageobject.web.portal.quotes.QuoteQueryPage;
import mercury.pageobject.web.portal.quotes.QuotesAwaitingReviewPage;
import mercury.pageobject.web.portal.quotes.QuotesInQueryPage;
import mercury.pageobject.web.portal.quotes.QuotesManagersDecisionPage;
import mercury.pageobject.web.portal.quotes.QuotesWithQueryPendingPage;
import mercury.pageobject.web.portal.quotes.QuotesWithQueryResponsePage;
import mercury.pageobject.web.portal.quotes.RegisterQuotePage;
import mercury.pageobject.web.portal.quotes.RejectQuoteRequest;
import mercury.pageobject.web.portal.quotes.SubmitQuoteJobRecommendModalPage;
import mercury.pageobject.web.portal.quotes.SubmitQuoteJobRejectionModalPage;
import mercury.pageobject.web.portal.quotes.SubmitQuoteQueryModalPage;
import mercury.pageobject.web.portal.quotes.UploadQuotePage;
import mercury.pageobject.web.portal.resources.JobsAwaitingReallocationForResourcePage;
import mercury.pageobject.web.portal.resources.JobsAwaitingReallocationPage;
import mercury.pageobject.web.portal.resources.OnCallSchedulerPage;
import mercury.pageobject.web.portal.resources.OnCallSummaryPage;
import mercury.pageobject.web.portal.resources.ResourceAvailabilityPage;
import mercury.pageobject.web.servicechannel.ServiceChannelHomePage;
import mercury.pageobject.web.servicechannel.ServiceChannelJobDetailsPage;
import mercury.pageobject.web.servicechannel.ServiceChannelLoginPage;
import mercury.pageobject.web.servicechannel.ServiceChannelSearchResultsPage;
import mercury.pageobject.web.storeportal.StorePortalCalendarPage;
import mercury.pageobject.web.storeportal.StorePortalContactUsMenuPage;
import mercury.pageobject.web.storeportal.StorePortalContactUsModal;
import mercury.pageobject.web.storeportal.StorePortalHomePage;
import mercury.pageobject.web.storeportal.StorePortalJobDetailsPage;
import mercury.pageobject.web.storeportal.StorePortalLeaveFeedbackModal;
import mercury.pageobject.web.storeportal.StorePortalLogAJobPage;
import mercury.pageobject.web.storeportal.StorePortalLoginPage;

public class RuntimeState {

    public Scenario scenario;

    public LoginPage loginPage;
    public PasswordResetRequestPage passwordResetRequestPage;
    public ResetPasswordPage resetPasswordPage;
    public String timezone;
    public String deployedVersion;
    public List<Resource> originalResources = new ArrayList<>();
    public JobQuestions jobQuestions;
    public String timestamp; // at start of scenario
    public String domainUser;

    public PopupAlert popupAlert;

    // admin pages
    public AdminHomePage adminHomePage;
    public AdminQuestionPage adminQuestionPage;
    public AdminRefrigerantGasUsageEditPage adminRefrigerantGasUsageEditPage;       // UK Regulations
    public AdminRefrigerantGasUsageEditPageV2 adminRefrigerantGasUsageEditPageV2;   // US Regulations
    public AdminRefrigerantGasUsageSearchPage adminRefrigerantGasUsageSearchPage;
    public AdminRefrigerantSourceModal adminRefrigerantSourceModal;
    public AdminRulesEnginePage adminRulesEnginePage;
    public AdminIncidentConfigurationPage adminIncidentConfigurationPage;
    public AdminNewIncidentCriteriaPage adminNewIncidentCriteriaPage;
    public AdminEditIncidentCriteriaPage adminEditIncidentCriteriaPage;
    public AdminEditResourcePage adminEditResourcePage;
    public AdminRulePage adminRulePage;
    public AdminLeakSiteInformationModal adminLeakSiteInformationModal;
    public AdminSystemFeatureTogglePage adminSystemFeatureTogglePage;
    public AdminMenuPage adminMenuPage;
    public AdminFinancePage adminFinancePage;
    public AdminCompaniesPage adminCompaniesPage;
    public AdminEditCompanyPage adminEditCompanyPage;
    public AdminEditCompanyCoreDetailsPartial adminEditCompanyCoreDetailsPartial;
    public AdminEditCompanyAdditionalDetailsPartial adminEditCompanyAdditionalDetailsPartial;
    public AdminEditCompanySaveModal adminEditCompanySaveModal;
    public AdminEditCompanyAliasesPartial adminEditCompanyAliasesPartial;
    public AdminCompaniesAssignmentRulesPage adminCompaniesAssignmentRulesPage;
    public AdminCompaniesAddAssignmentRulePage adminCompaniesAddAssignmentRulePage;
    public AdminCompaniesAssignmentRuleEditPage adminCompaniesAssignmentRuleEditPage;
    public AdminCompaniesAssignmentRuleDeleteModal adminCompaniesAssignmentRuleDeleteModal;
    public AdminCompaniesEditAssignmentRuleModal adminCompaniesEditAssignmentRuleModal;
    public AdminResourcesAndUsersPage adminResourcesAndUsersPage;
    public NewInvoicingEditInvoiceLineModal newInvoicingEditInvoiceLineModal;
    public EditInvoiceLineConfirmationModal editInvoiceLineConfirmationModal;
    public AdminJobsPage adminJobsPage;
    public AdminJobStatusEditPage adminJobStatusEditPage;
    public OnCallSchedulerAdminPage onCallSchedulerAdminPage;
    public AdminAddNewUserProfilePage adminAddNewUserProfilePage;
    public AdminAddNewResourcePage adminAddNewResourcePage;
    public AdminEditSiteConfigurationModal adminEditSiteConfigurationModal;
    public AdminEditUserProfilePage adminEditUserProfilePage;
    public AdminAddNewResourceProfilePage adminAddNewResourceProfilePage;
    public AdminSitesPage adminSitesPage;
    public AdminAddNewUserPage adminAddNewUserPage;
    public AdminEditResourceProfilePage adminEditResourceProfilePage;
    public AdminEditUserPage adminEditUserPage;
    public AdminEditSitePage adminEditSitePage;
    public AdminSiteTypesPage adminSiteTypesPage;
    public AdminOrganisationPage adminOrganisationPage;
    public AdminEditSiteTypePage adminEditSiteTypePage;
    public AdminImportConfigurationPage adminImportConfigurationPage;
    public AdminConfigureExceptionModal adminConfigureExceptionModal;
    public AdminEditOrderWidget adminEditOrderWidget;
    public AdminAssetsPage adminAssetsPage;
    public AdminAddNewAssetPage adminAddNewAssetPage;
    public AdminEditAssetPage adminEditAssetPage;
    public AdminPpmsPage adminPpmsPage;
    public AdminAddNewPpmTypePage adminAddNewPpmTypePage;
    public AdminPpmTypeAssetPage adminPpmTypeAssetPage;
    public AdminPpmTypeAssetMappingPage adminPpmTypeAssetMappingPage;
    public AdminComplianceConfigPage adminComplianceConfigPage;


    // helpdesk pages
    public HelpdeskAddCallerPage helpdeskAddCallerPage;
    public HelpdeskAddAdditionalResourcePanel helpdeskAddAdditionalResourcePanel;
    public HelpdeskAdditionalResourcePanel helpdeskAdditionalResourcePanel;
    public HelpdeskAdviseEtaPanel helpdeskAdviseEtaPanel;
    public HelpdeskAssetPage helpdeskAssetPage;
    public HelpdeskCallerPage helpdeskCallerPage;
    public HelpdeskCallJobContactModal helpdeskCallJobContactModal;
    public HelpdeskCoreDetails helpdeskCoreDetails;
    public HelpdeskHomePage helpdeskHomePage;
    public HelpdeskJobCancelPanel helpdeskJobCancelPanel;
    public HelpdeskJobPage helpdeskJobPage;
    public HelpdeskLogJobPage helpdeskLogJobPage;
    public HelpdeskLogAnIncidentPage helpdeskLogAnIncidentPage;
    public HelpdeskManageResourcesPanel helpdeskManageResourcesPanel;
    public HelpdeskOpenJobsTab helpdeskOpenJobsTab;
    public HelpdeskDocumentsTab helpdeskDocumentsTab;
    public HelpdeskQuotesPanel helpdeskQuotesPanel;
    public HelpdeskNavBar helpdeskNavBar;
    public HelpdeskResourcePage helpdeskResourcePage;
    public HelpdeskResourcesTab helpdeskResourcesTab;
    public HelpdeskSearchBar helpdeskSearchBar;
    public HelpdeskSitePage helpdeskSitePage;
    public HelpdeskTimelineTab helpdeskTimelineTab;
    public HelpdeskTriagePanel helpdeskTriagePanel;
    public HelpdeskJobActionsPanel helpdeskJobActionsPanel;
    public NewCallerPage newCallerPage;
    public HelpdeskFundingRequestsPanel helpdeskFundingRequestsPanel;
    public HelpdeskAcceptJobPanel helpdeskAcceptJobPanel;
    public HelpdeskJobChasePanel helpdeskJobChasePanel;
    public HelpdeskCreateJobChasePanel helpdeskCreateJobChasePanel;
    public HelpdeskUpdateJobChasePanel helpdeskUpdateJobChasePanel;
    public HelpdeskCancelJobChasePanel helpdeskCancelJobChasePanel;
    public HelpdeskQuestionsTab helpdeskQuestionsTab;
    public HelpdeskRemoveResourcePanel helpdeskRemoveResourcePanel;
    public HelpdeskAdviseRemovalPanel helpdeskAdviseRemovalPanel;
    public ReopenJobModal reopenJobModal;
    public AddJobNotesModal addJobNotesModal;
    public HelpdeskAddAttachmentsModal helpdeskAddAttachmentsModal;
    public HelpdeskLinkedJobsModal helpdeskLinkedJobsModal;
    public HelpdeskViewIncidentPage helpdeskViewIncidentPage;
    public HelpdeskIncidentTimelineTab helpdeskIncidentTimelineTab;
    public HelpdeskIncidentAnswersTab helpdeskIncidentAnswersTab;
    public HelpdeskParkJobPanel helpdeskParkJobPanel;
    public HelpdeskAdditionalResourcesRequiredPanel helpdeskAdditionalResourcesRequiredPanel;
    public HelpdeskAdditionalResourcesNotRequiredPanel helpdeskAdditionalResourcesNotRequiredPanel;
    public HelpdeskCancelIncidentPage helpdeskCancelIncident;
    public HelpdeskDeclineJobPanel helpdeskDeclineJobPanel;
    public HelpdeskScheduleCallBackPanel helpdeskScheduleCallBackPanel;
    public HelpdeskIncidentUpdate helpdeskIncidentUpdate;
    public HelpdeskIncidentsLinkedJobsModal helpdeskIncidentsLinkedJobsModal;
    public HelpdeskIncidentMonitorPage helpdeskIncidentMonitorPage;
    public HelpdeskIncidentFollowUpPage helpdeskIncidentFollowUpPage;
    public HelpdeskIncidentEscalation helpdeskIncidentEscalation;
    public HelpdeskIncidentSendEscalation helpdeskIncidentSendEscalation;
    public HelpdeskIncidentEscalationAdditionalContact helpdeskIncidentEscalationAdditionalContact;
    public HelpdeskIncidentActionsDropdown helpdeskIncidentActionsDropdown;
    public HelpdeskIncidentEscalationTab helpdeskIncidentEscalationTab;
    public ConfirmJobChangesModal confirmJobChangesModal;
    public CancelChangesAlert cancelChangesAlert;
    public HelpdeskJobsLinkedIncidentsPanel helpdeskJobsLinkedIncidentsPanel;
    public HelpdeskContactsTab helpdeskContactsTab;
    public HelpdeskPreviousFundingRequestsPanel helpdeskPreviousFundingRequestsPanel;
    public HelpdeskAcknowledgeETAPanel helpdeskAcknowledgeETAPanel;
    public EditCallerModal editCallerModal;
    public MonitorGrid monitorGrid;
    public MonitorsToDo monitorsToDo;
    public MonitorsForInfo monitorsForInfo;
    public MonitorsSettings monitorsSettings;
    public HelpdeskResourceETAPanel helpdeskResourceETAPanel;
    public HelpdeskCancelApprovedUpliftPanel helpdeskCancelApprovedUpliftPanel;
    public HelpdeskAddOrOverrideAbsencePanel helpdeskAddOrOverrideAbsencePanel;
    public HelpdeskIncidentEscalationContactEmailSmsTab helpdeskIncidentEscalationContactEmailSmsTab;
    public HelpdeskNewSiteContactModal helpdeskNewSiteContactModal;
    public HelpdeskLinkedIncidentsModal helpdeskLinkedIncidentsModal;
    public HelpdeskTransferWorkPanel helpdeskTransferWorkPanel;
    public ConfirmWarrantyPanel confirmWarrantyPanel;

    // portal pages
    public AcceptJobPage acceptJobPage;
    public AddNewCreditNoteLineModal addNewCreditNoteLineModal;
    public AddNewInvoiceLineModal addNewInvoiceLineModal;
    public AddOrderLineToInvoiceModal addOrderLineToInvoiceModal;
    public AddOrderLinesToInvoiceConfirmationModal addOrderLinesToInvoiceConfirmationModal;
    public AddQuoteLinePage addQuoteLinePage;
    public AllCreditNotesAwaitingApprovalPage allCreditNotesAwaitingApprovalPage;
    public AllInvoicesAwaitingApprovalPage allInvoicesAwaitingApprovalPage;
    public AllJobsPage allJobsPage;
    public AllJobsPage_OpsDirector allJobsPage_OpsDirector;
    public AllOrdersPage allOrdersPage;
    public ApproveInvoiceModalPage approveInvoiceModalPage;
    public AsbestosModal asbestosModal;
    public ChooseAssetPage chooseAssetPage;
    public ClosedownTab closedownTab;
    public ContactInfoJobDetailsPage contactInfoJobDetailsPage;
    public ConsolidatedInvoicesInProgressPage consolidatedInvoicesInProgressPage;
    public CreateCreditNotePage createCreditNotePage;
    public CreatePartRequestModalPage createPartRequestModalPage;
    public CreateQuotePage createQuotePage;
    public CreditNoteApprovalPage creditNoteApprovalPage;
    public CreditNoteLinesModal creditNoteLinesModal;
    public CreditNotePage creditNotePage;
    public DeclineInvitationToQuotePage declineInvitationToQuotePage;
    public DeleteInvoiceDocModal deleteInvoiceDocModal;
    public DeleteQuoteLinePage deleteQuoteLinePage;
    public EditInvoiceLineModal editInvoiceLineModal;
    public EditQuoteDetailsPage editQuoteDetailsPage;
    public EnterCreditNoteDetailsPage enterCreditNoteDetailsPage;
    public FeedbackPage feedbackPage;
    public FeedbackDetailsModal feedbackDetailsModal;
    public FeedbackResponsePage feedbackResponsePage;
    public FundingRequestsAwaitingResponseReviewPage fundingRequestsAwaitingResponseReviewPage;
    public FundingRequestQueriesPage fundingRequestQueriesPage;
    public FundingRequestsAwaitingApprovalPage fundingRequestsAwaitingApprovalPage;
    public FundingRequestsAwaitingReviewPage fundingRequestsAwaitingReviewPage;
    public FundingRequestsPendingQueryResponsePage fundingRequestsPendingQueryResponsePage;
    public FundingRequestsRejectedPage fundingRequestsRejectedPage;
    public FundingRouteModal fundingRouteModal;
    public InitialFundingRequestsApprovalPage initialFundingRequestsApprovalPage;
    public InitialFundingRequestsPage initialFundingRequestsPage;
    public InvoiceApprovalPage invoiceApprovalPage;
    public InvoiceDeleteInvoiceTemplateModal invoiceDeleteInvoiceTemplateModal;
    public InvoiceDetailsPage invoiceDetailsPage;
    public InvoiceFinalApprovalPage invoiceFinalApprovalPage;
    public InvoiceLinesModal invoiceLinesModal;
    public InvoicePendingReviewPage invoicePendingReviewPage;
    public InvoiceReassignApproverPage invoiceReassignApproverPage;
    public InvoiceSubmittedPage invoiceSubmittedPage;
    public InvoiceTab invoiceTabPage;
    public InvoiceTemplatePage invoiceTemplatePage;
    public InvoiceTemplatesPage invoiceTemplatesPage;
    public InvoicesAndCreditsAllOrders invoicesAndCreditsAllOrders;
    public InvoicesAndCreditsAwaitingReviewPage invoicesAndCreditsAwaitingReviewPage;
    public InvoicesAwaitingApprovalPage invoicesAwaitingApprovalPage;
    public InvoicesAwaitingFinalApprovalPage invoicesAwaitingFinalApprovalPage;
    public InvoicesAwaitingReviewPage invoicesAwaitingReviewPage;
    public InvoiceViewPage invoiceViewPage;
    public JobAwaitingResourceAssignmentPage jobAwaitingResourceAssignmentPage;
    public JobDetailsPage jobDetailsPage;
    public JobDetailsPartial jobDetailsPartial;
    public JobHistoryPage jobHistoryPage;
    public JobInfoJobDetailsPage jobInfoJobDetailsPage;
    public JobLoggedConfigmationPage jobLoggedConfigmationPage;
    public JobNotesTab jobNotesTab;
    public JobCostsTab jobCostsTab;
    public JobsAwaitingQuotePage jobsAwaitingQuotePage;
    public JobsAwaitingReallocationPage jobsAwaitingReallocationPage;
    public JobsAwaitingReallocationForResourcePage jobsAwaitingReallocationForResourcePage;
    public JobsAwaitingResourceSelectionPage jobsAwaitingResourceSelectionPage;
    public ManageDeptHeadUserAssignmentPage manageDeptHeadUserAssignmentPage;
    public ManageInvoiceLinesModal manageInvoiceLinesModal;
    public ManagerJobsAwaitingQuotePage managerJobsAwaitingQuotePage;
    public MultiQuoteAwaitingBypassApprovalPage multiQuoteAwaitingBypassApprovalPage;
    public MultiQuoteAwaitingBypassReviewPage multiQuoteAwaitingBypassReviewPage;
    public MultiQuoteAwaitingQuotePage multiQuoteAwaitingQuotePage;
    public MultiQuoteAwaitingResourceSelectionPage multiQuoteAwaitingResourceSelectionPage;
    public MultiQuoteAwaitingReviewPage multiQuoteAwaitingReviewPage;
    public OrdersAwaitingInvoicePage ordersAwaitingInvoicePage;
    public OnCallSummaryPage onCallSummaryPage;
    public OnCallSchedulerPage onCallSchedulerPage;
    public OpenAwaitingJobsPage openAwaitingJobsPage;
    public OpenQuoteRequestsPage openQuoteRequestsPage;
    public PartsOrderAwaitingApprovalPage partsOrderAwaitingApprovalPage;
    public PartsRequestPage partsRequestPage;
    public PartsRequestsAwaitingApprovalPage partsRequestsAwaitingApprovalPage;
    public PortalAppliancePartial portalAppliancePartial;
    public PortalConsolidatedInvoicePage portalConsolidatedInvoicePage;
    public PortalHomePage portalHomePage;
    public PortalJobsForSitePage portalJobsForSitePage;
    public PortalLeakCheckAppliancePartial portalLeakCheckAppliancePartial;
    public PortalLeakSiteInformationModal portalLeakSiteInformationModal;
    public PortalLeakSiteInformationPartial portalLeakSiteInformationPartial;
    public PortalLogAJobPage portalLogAJobPage;
    public PortalNavBar portalNavBar;
    public PortalOpenJobsBySitePage portalOpenJobsBySitePage;
    public PortalOrdersInvoicePage portalOrdersInvoicePage;
    public PortalRefrigerantMaxChargePartial portalRefrigerantMaxChargePartial;
    public PortalRefrigerantSourceModal portalRefrigerantSourceModal;
    public PortalRefrigerantSourcePartial portalRefrigerantSourcePartial;
    public PortalRefrigerantVersion1 portalRefrigerantVersion1;
    public PortalStartWorkModalPage portalStartWorkModalPage;
    public PortalSummaryPage portalSummaryPage;
    public PortalUpdateJobETA portalUpdateJobETA;
    public PPMAddCertificatesModal ppmAddCertificatesModal;
    public PPMGasSafetyAdviceNoticeModal ppmGasSafetyAdviceNoticeModal;
    public PPMJobDetailsPage ppmJobDetailsPage;
    public PPMRemedialJobPage ppmRemedialJobPage;
    public PPMRequestQuotePage ppmRequestQuotePage;
    public QueryInitialApproverModal queryInitialApproverModal;
    public QuestionHelper questionHelper;
    public QuoteAwaitingResourceQuotePage quoteAwaitingResourceQuotePage;
    public QuoteJobDetailsPage quoteJobDetailsPage;
    public QuoteJobEdit quoteJobEdit;
    public QuoteQueryPage quoteQueryPage;
    public QuotesAwaitingReviewPage quotesAwaitingReviewPage;
    public QuotesInQueryPage quotesInQueryPage;
    public QuotesManagersDecisionPage quotesManagersDecisionPage;
    public QuotesWithQueryPendingPage quotesWithQueryPendingPage;
    public QuotesWithQueryResponsePage quotesWithQueryResponsePage;
    public ResourceAvailabilityPage resourceAvailabilityPage;
    public RegisterQuotePage registerQuotePage;
    public RejectCreditNoteModal rejectCreditNoteModal;
    public RejectInvoiceModalPage rejectInvoiceModalPage;
    public RejectInvoicePendingReviewModal rejectInvoicePendingReviewModal;
    public RejectQuoteRequest rejectQuoteRequest;
    public ReplyToStoreModal replyToStoreModal;
    public SiteInfoJobDetailsPage siteInfoJobDetailsPage;
    public SpokeToStoreModal spokeToStoreModal;
    public SubmitFundingRequestModalPage submitFundingRequestModalPage;
    public SubmitQuoteJobRejectionModalPage submitQuoteJobRejectionModalPage;
    public SubmitQuoteJobRecommendModalPage submitQuoteJobRecommendModalPage;
    public SubmitQuoteQueryModalPage submitQuoteQueryModalPage;
    public SubmittedInvoicesAndCreditsPage submittedInvoicesAndCreditsPage;
    public UpdateJobPage updateJobPage;
    public UpdateSavedPage updateSavedPage;
    public UpliftsTab upliftsTabPage;
    public UploadCreditNoteDocumentPage uploadCreditNoteDocumentPage;
    public UploadInvoiceDocumentPage uploadInvoiceDocumentPage;
    public UploadInvoiceDocumentsPage uploadInvoiceDocumentsPage;
    public UploadQuotePage uploadQuotePage;

    // store portal pages
    public StorePortalLoginPage storePortalLoginPage;
    public StorePortalHomePage storePortalHomePage;
    public StorePortalCalendarPage storePortalCalendarPage;
    public StorePortalJobDetailsPage storePortalJobDetailsPage;
    public StorePortalContactUsModal storePortalContactUsModal;
    public StorePortalLeaveFeedbackModal storePortalLeaveFeedbackModal;
    public StorePortalLogAJobPage storePortalLogAJobPage;
    public StorePortalContactUsMenuPage storePortalContactUsMenuPage;

    // service channel pages
    public ServiceChannelLoginPage serviceChannelLoginPage;
    public ServiceChannelHomePage serviceChannelHomePage;
    public ServiceChannelSearchResultsPage serviceChannelSearchResultsPage;
    public ServiceChannelJobDetailsPage serviceChannelJobDetailsPage;

    // Notifications Url Pages
    public NotificationPage notificationPage;

}