USE [%testdb]
GO

SET IDENTITY_INSERT GasQuestionAnswerSet ON;  
GO
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('1811', '1', '454', '0', '0', '-1', '0', '1357', NULL, NULL, 'System', '2018-08-15 17:24:43.32', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('1812', '2', '455', '0', '0', '-1', '0', '1357', NULL, NULL, 'System', '2018-08-15 17:24:43.32', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('1813', '1', '456', '0', '0', '-1', '1', '1358', NULL, NULL, 'System', '2018-08-15 17:24:43.32', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('1814', '2', '457', '0', '0', '-1', '0', '1358', NULL, NULL, 'System', '2018-08-15 17:24:43.32', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('1815', '1', '458', '0', '0', '-1', '0', '1363', NULL, NULL, 'System', '2018-08-15 18:00:26.283', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('1816', '1', '459', '0', '0', '-1', '0', '1359', NULL, NULL, 'System', '2018-08-16 15:59:37.627', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('1817', '1', '460', '0', '0', '-1', '0', '1398', NULL, NULL, 'System', '2018-08-20 12:18:20.413', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('1818', '2', '461', '0', '0', '-1', '0', '1398', NULL, NULL, 'System', '2018-08-20 12:18:20.413', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('1819', '1', '462', '0', '0', '-1', '0', '1402', NULL, NULL, 'System', '2018-08-20 12:18:28.607', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('1820', '2', '463', '0', '0', '-1', '0', '1402', NULL, NULL, 'System', '2018-08-20 12:18:28.607', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('1821', '1', '465', '0', '0', '-1', '0', '1405', NULL, NULL, 'System', '2018-08-28 19:55:43.483', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('2811', '1', '454', '0', '0', '-1', '0', '2357', NULL, NULL, 'System', '2018-08-21 08:02:35.517', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('2812', '2', '455', '0', '0', '-1', '0', '2357', NULL, NULL, 'System', '2018-08-21 08:02:35.52', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('2813', '1', '456', '0', '0', '-1', '1', '2358', NULL, NULL, 'System', '2018-08-21 08:02:35.523', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('2814', '2', '457', '0', '0', '-1', '0', '2358', NULL, NULL, 'System', '2018-08-21 08:02:35.547', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('2815', '1', '458', '0', '0', '-1', '0', '2363', NULL, NULL, 'System', '2018-08-21 08:02:35.55', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('2816', '1', '459', '0', '0', '-1', '0', '2359', NULL, NULL, 'System', '2018-08-21 08:02:35.557', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('3811', '1', '454', '0', '0', '-1', '0', '3357', NULL, NULL, 'System', '2018-08-21 13:47:14.977', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('3812', '2', '455', '0', '0', '-1', '0', '3357', NULL, NULL, 'System', '2018-08-21 13:47:14.983', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('3813', '1', '456', '0', '0', '-1', '1', '3358', NULL, NULL, 'System', '2018-08-21 13:47:14.987', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('3814', '2', '457', '0', '0', '-1', '0', '3358', NULL, NULL, 'System', '2018-08-21 13:47:14.99', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('3815', '1', '458', '0', '0', '-1', '0', '3363', NULL, NULL, 'System', '2018-08-21 13:47:15.017', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('3816', '1', '459', '0', '0', '-1', '0', '3359', NULL, NULL, 'System', '2018-08-21 13:47:15.023', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4811', '1', '454', '0', '0', '-1', '0', '4357', NULL, NULL, 'System', '2018-08-23 05:37:27.25', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4812', '2', '455', '0', '0', '-1', '0', '4357', NULL, NULL, 'System', '2018-08-23 05:37:27.253', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4813', '1', '456', '0', '0', '-1', '1', '4358', NULL, NULL, 'System', '2018-08-23 05:37:27.26', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4814', '2', '457', '0', '0', '-1', '0', '4358', NULL, NULL, 'System', '2018-08-23 05:37:27.26', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4815', '1', '458', '0', '0', '-1', '0', '4363', NULL, NULL, 'System', '2018-08-23 05:37:27.263', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4816', '1', '459', '0', '0', '-1', '0', '4359', NULL, NULL, 'System', '2018-08-23 05:37:27.267', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4817', '1', '460', '0', '0', '-1', '0', '4376', NULL, NULL, 'System', '2018-08-25 05:47:28.75', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4818', '2', '461', '0', '0', '-1', '0', '4376', NULL, NULL, 'System', '2018-08-25 05:47:28.75', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4821', '1', '500', '0', '0', '-1', '0', '4381', NULL, NULL, 'System', '2018-08-28 19:55:01.963', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4822', '2', '501', '0', '0', '-1', '0', '4381', NULL, NULL, 'System', '2018-08-28 19:55:01.963', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4823', '3', '502', '0', '0', '-1', '0', '4381', NULL, NULL, 'System', '2018-08-28 19:55:01.963', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4824', '4', '503', '0', '0', '-1', '0', '4381', NULL, NULL, 'System', '2018-08-28 19:55:01.963', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4825', '5', '504', '0', '0', '-1', '0', '4381', NULL, NULL, 'System', '2018-08-28 19:55:01.963', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4826', '6', '505', '0', '0', '-1', '0', '4381', NULL, NULL, 'System', '2018-08-28 19:55:01.963', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4827', '1', '506', '0', '0', '-1', '0', '4383', NULL, NULL, 'System', '2018-08-28 19:55:33.683', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4828', '2', '507', '0', '0', '-1', '0', '4383', NULL, NULL, 'System', '2018-08-28 19:55:33.683', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4829', '1', '508', '0', '0', '-1', '0', '4384', NULL, NULL, 'System', '2018-08-28 19:55:43.483', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4931', '2', '509', '0', '0', '-1', '0', '4384', NULL, NULL, 'System', '2018-08-28 19:55:43.483', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4932', '1', '514', '0', '0', '-1', '0', '4504', NULL, NULL, 'System', '2018-08-15 17:24:43.32', NULL, NULL, NULL);
insert into GasQuestionAnswerSet (Id, Seq, AnsFk, Parentid, Reportable, NextQuestion, DefaultFlag, QuestionFk, PdfAlias, PdfNIAlias, Createdby, Createdon, Lastmodifiedby, Lastmodifiedon, AppActionSetID) values ('4933', '2', '515', '0', '0', '-1', '0', '4504', NULL, NULL, 'System', '2018-08-15 17:24:43.32', NULL, NULL, NULL);
GO
SET IDENTITY_INSERT GasQuestionAnswerSet OFF; 
GO